[build]
builder = "nixpacks"
buildCommand = "npx prisma generate --schema=packages/database/prisma/schema.prisma && SKIP_ENV_VALIDATION=1 npm run build --workspace=apps/web"

[deploy]
startCommand = "npx prisma migrate deploy --schema=packages/database/prisma/schema.prisma && npm run start --workspace=apps/web"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
